---
title: if...else
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---





= if (conditional) and ==, !=, <, > (comparison operators)


// OVERVIEW SECTION STARTS
[#overview]
--
[float]
=== Description
The `if` statement checks for a condition and executes the following statement (see definition of statement below) if the condition is 'true'. If `else` follows the statemnt, the statement following the `else` is executed. if the condition is false.  A statement is (1) one command, or (2) a collection of 0 or more commands enclosed with braces (curly brackets {}).
[%hardbreaks]

[float]
=== Syntax
[source,arduino]
----
if (condition)
  //statement to be executed if condition is true 
[else 
  //statement to be executed if condition is false
]
----

[float]
=== Parameters
condition: a boolean expression i.e., can be `true` or `false`

[float]
=== Example Code

Definition of statement:   

[%hardbreaks]

[source,arduino]
----
if (x > 120) digitalWrite(LEDpin, HIGH);

if (x > 120)
digitalWrite(LEDpin, HIGH);

if (x > 120){ digitalWrite(LEDpin, HIGH); }

if (x > 120){
  digitalWrite(LEDpin1, HIGH);
  digitalWrite(LEDpin2, HIGH);
}                                 

if (x > 120) digital
  digitalWrite(LEDpin1, HIGH);
else
  digitalWrite(LEDpin2, HIGH);

if (x > 120) digital {
  digitalWrite(LEDpin1, HIGH);
}
else
  digitalWrite(LEDpin2, HIGH);

                   // all are correct

Note that 

if (x > 120) digital {
  digitalWrite(LEDpin1, HIGH);
  digitalWrite(LEDpin2, HIGH);
}
else {
  digitalWrite(LEDpin3, HIGH);
  digitalWrite(LEDpin4, HIGH);
}

is not the same as

if (x > 120) digital {
  digitalWrite(LEDpin1, HIGH);
  digitalWrite(LEDpin2, HIGH);
}
else 
  digitalWrite(LEDpin3, HIGH);
  digitalWrite(LEDpin4, HIGH);  // this command would always be executed

and that

if (x > 120) digital 
  digitalWrite(LEDpin1, HIGH);
  digitalWrite(LEDpin2, HIGH);
else {
  digitalWrite(LEDpin3, HIGH);
  digitalWrite(LEDpin4, HIGH);
}

will get a compiler error because there is more than one statement between the `else` and the `if`
----
[%hardbreaks]


[float]
=== Notes and Warnings
The statements being evaluated inside the parentheses require the use of one or more operators shown below.
[%hardbreaks]

*Comparison Operators:*

 x == y (x is equal to y)
 x != y (x is not equal to y)
 x <  y (x is less than y)
 x >  y (x is greater than y)
 x <= y (x is less than or equal to y)
 x >= y (x is greater than or equal to y)


Beware of accidentally using the single equal sign (e.g. `if (x = 10)` ). The single equal sign is the assignment operator, and sets `x` to 10 (puts the value 10 into the variable `x`). Instead use the double equal sign (e.g. `if (x == 10)` ), which is the comparison operator, and tests _whether_ `x` is equal to 10 or not. The latter statement is only true if `x` equals 10, but the former statement will always be true.

This is because C evaluates the statement `if (x=10)` as follows: 10 is assigned to `x` (remember that the single equal sign is the (http://arduino.cc/en/Reference/Assignment[assignment operator^])), so `x` now contains 10. Then the 'if' conditional evaluates 10, which always evaluates to `TRUE`, since any non-zero number evaluates to TRUE. Consequently, `if (x = 10)` will always evaluate to `TRUE`, which is not the desired result when using an 'if' statement. Additionally, the variable `x` will be set to 10, which is also not a desired action.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
